Etapa 2: Desarrollo SE2
FabriCubi/kafka-kit pull request #1
Opened 2021-05-31 17:15 UTC by FabriCubi

2021-05-31 21:42 UTC, scanterog requested changes

2021-05-31 21:42 UTC, scanterog commented on kafkaadmin/kafkaadmin.go
> +	GetTopics() ([]string, error)
Debería de recibir una lista de regex como parametro: ts []*regexp.Regexp.
ref: https://github.com/DataDog/kafka-kit/blob/v3.7.0/kafkazk/zookeeper.go#L364

2021-05-31 21:42 UTC, scanterog commented on kafkaadmin/client.go
> +	Prefix string
Para que necesitas Prefix? Esto solo se usa para ZK.

2021-05-31 21:42 UTC, scanterog commented on kafkaadmin/topics.go
> +in: none
Seguí el formato de comentario que se usa en el repo. Esto no es necesario.

2021-05-31 21:42 UTC, scanterog commented on kafkaadmin/topics.go
> +	if c.Prefix != "" {
esto está mal. El signature de GetMetadata es:
```
func (a *AdminClient) GetMetadata(topic *string, allTopics bool, timeoutMs int) (*Metadata, error) {
```
No podes pasar "path" como primer parametro. Eso es especifico de ZK. En tu caso particular de traer "todos" los topics del cluster, tenes que llamar con GetMetadata(nil, true, timeout). El timeout generalmente se abstrae al inicio del archivo go. Algo como:
```
const FetchMetadataTimeoutMs = 1000
```

2021-05-31 21:42 UTC, scanterog commented on kafkaadmin/topics.go
> +	if c.Prefix != "" {
Mismo comentario con la funcion anterior

2021-05-31 21:42 UTC, scanterog commented on kafkaadmin/topics.go
> +	Partitions map[string][]int `json:"partitions"`
No hay ningun json que deserializar acá. La función te retorna [Metadata](https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/metadata.go#L70).

2021-05-31 21:42 UTC, scanterog commented on kafkaadmin/topics.go
> +	ret, er := c.c.GetMetadata(&path, true, TIMEOUT)
En lugar de solicitar metadata para todos los topics tenes que solicitar solo para ese topic particular. Mira la definición de GetMetadata()

2021-05-31 21:42 UTC, scanterog commented on kafkaadmin/topics.go
> +	return topicsList, nil
debería de retornar solo los que hacen match del regex

2021-05-31 21:42 UTC, scanterog commented on kafkaadmin/topics.go
> +	if ret.Topics[t].Topic != "" {
Este se puede mejorar bastante al solicitar para un solo topic.

2021-05-31 21:42 UTC, scanterog commented on kafkaadmin/topics.go
> +		for _, item := range topics.Partitions {
Estas conversiones parecen innecesarias. Yo consideraría cambiar TopicState a:
```
type TopicState struct {
  Partitions map[int32][]int32 
}
```
Y dejar que upstream defina si es necesario hacer las conversiones.

2021-05-31 21:42 UTC, scanterog commented on go.mod
> +	google.golang.org/protobuf v1.26.0 // indirect
pq se actualizó esto si no se hizo ningún cambio relacionado protobuf?

2021-06-03 02:34 UTC, FabriCubi commented on kafkaadmin/kafkaadmin.go
> +	GetTopics() ([]string, error)
Ok, modificado.

2021-06-03 02:34 UTC, FabriCubi commented on kafkaadmin/client.go
> +	Prefix string
Ok Modificado, pensaba que era necesario para esta también.

2021-06-03 02:34 UTC, FabriCubi commented on kafkaadmin/topics.go
> +in: none
Ok, modificado.

2021-06-03 02:35 UTC, FabriCubi commented on kafkaadmin/topics.go
> +	Partitions map[string][]int `json:"partitions"`
OK, modificado.

2021-06-03 02:35 UTC, FabriCubi commented on kafkaadmin/topics.go
> +	return topicsList, nil
Ok, modificado.

2021-06-03 02:35 UTC, FabriCubi commented on go.mod
> +	google.golang.org/protobuf v1.26.0 // indirect
[warns], eran dependencias indirectas, no figura en go.mod su dependencia directa, pero que es necesaria, creo que para el github.com/DataDog/kafka-kit/v3/registry/protos

2021-06-03 02:36 UTC, FabriCubi commented on kafkaadmin/topics.go
> +		for _, item := range topics.Partitions {
Ok, modificado no sabia que tantos cambios tenia permitido. Quería que sea lo más parecido al que usa Zk. (En cuanto al return) dejo para el upstream

2021-06-03 03:02 UTC, FabriCubi commented on kafkaadmin/topics.go
> +	if c.Prefix != "" {
Ok, modificado. En que parte mismo pongo el FecthMetadaTimeoutMs? dentro de mi metodo O en un archivo especifico, por ejemplo topics.go como "const package level" (Global)?

2021-06-03 03:41 UTC, FabriCubi commented on kafkaadmin/topics.go
> +	ret, er := c.c.GetMetadata(&path, true, TIMEOUT)
GetMetadata( &t, false, FetchMetadaTimeoutMs) 
 - Si el topic NO existe crea uno por default. 
 - Si existe el topic funciona bien. 

Ayuda?

2021-06-09 18:57 UTC, scanterog commented on kafkaadmin/topics.go
> +//names that match any of the provided regex, and query kafka directrly rather than zk
```suggestion
// GetTopics takes a []*regexp.Regexp and returns a []string of all topic names 
// that match any of the provided regex.
```

2021-06-09 18:57 UTC, scanterog commented on kafkaadmin/topics.go
> +	ret, er := c.c.GetMetadata(nil, true, FetchMetadaTimeoutMs)
```suggestion
	metadata, err := c.c.GetMetadata(nil, true, FetchMetadataTimeoutMs)
```
`metadata` o `md` se entiende mas que ret

2021-06-09 18:57 UTC, scanterog commented on kafkaadmin/topics.go
> +		if ts[0].MatchString(topic) {
evalua un solo regex. Si tenes multiples, va a ignorar el resto.

2021-06-09 18:57 UTC, scanterog commented on kafkaadmin/topics.go
> +//TopicState struct
```suggestion
// TopicState represents the partition distribution of a single topic
```

2021-06-09 18:57 UTC, scanterog commented on kafkaadmin/topics.go
> +//the topic state is returned as a *TopicState, this query kafka directly rather than zk
```suggestion
// GetTopicState takes a topic name. If the topic exists, the topic state is returned as *TopicState.
```

2021-06-09 18:57 UTC, scanterog commented on kafkaadmin/topics.go
> +	ret, er := c.c.GetMetadata(&t, false, FetchMetadaTimeoutMs)
```suggestion
	metadata, err := c.c.GetMetadata(&t, false, FetchMetadataTimeoutMs)
```

2021-06-09 18:57 UTC, scanterog commented on kafkaadmin/topics.go
> +	if ret.Topics[t].Error.String() != "Success" {
```suggestion
	if metadata.Topics[t].Error != nil {
```

2021-06-09 18:57 UTC, scanterog commented on kafkaadmin/topics.go
> +	return tsf, nil
```suggestion

	return &TopicState{Partitions: partitions}, nil
```

2021-06-09 18:57 UTC, scanterog commented on kafkaadmin/topics.go
> +// is returned as a *TopicConfig,  this query kafka directly rather than zk.
```suggestion
// GetTopicConfig takes a topic name. If the topic exists, the topic config
// is returned as a *TopicConfig.
```

2021-06-09 18:57 UTC, scanterog commented on kafkaadmin/topics.go
> +	ret, er := c.c.DescribeConfigs(context.Background(),
```suggestion
	configResult, err := c.c.DescribeConfigs(context.Background(),
```

2021-06-09 18:57 UTC, scanterog commented on kafkaadmin/topics.go
> +	if ret[0].Error.String() != "Success" {
```suggestion
	if configResult[0].Error != nil {
```

2021-06-09 18:57 UTC, scanterog commented on kafkaadmin/topics.go
> +		return nil, ret[0].Error
```suggestion
		return nil, configResult[0].Error
```

2021-06-09 18:57 UTC, scanterog commented on kafkaadmin/topics.go
> +		Version: 1,
quizas esta version se podria borrar nomas si la API no retorna ninguna.

2021-06-10 01:16 UTC, FabriCubi commented on kafkaadmin/client.go
> +const FetchMetadaTimeoutMs = 1000 //int(time.Millisecond)
Ok, modificado.

2021-06-10 01:18 UTC, FabriCubi commented on kafkaadmin/topics.go
> +//names that match any of the provided regex, and query kafka directrly rather than zk
Ok, modificado.

2021-06-10 01:19 UTC, FabriCubi commented on kafkaadmin/topics.go
> +	ret, er := c.c.GetMetadata(nil, true, FetchMetadaTimeoutMs)
Ok, modificado.

2021-06-10 01:19 UTC, FabriCubi commented on kafkaadmin/topics.go
> +		if ts[0].MatchString(topic) {
Ok, solucionado.

2021-06-10 01:20 UTC, FabriCubi commented on kafkaadmin/topics.go
> +//TopicState struct
Ok, modificado.

2021-06-10 01:20 UTC, FabriCubi commented on kafkaadmin/topics.go
> +//the topic state is returned as a *TopicState, this query kafka directly rather than zk
Ok, modificado.

2021-06-10 01:21 UTC, FabriCubi commented on kafkaadmin/topics.go
> +	ret, er := c.c.GetMetadata(&t, false, FetchMetadaTimeoutMs)
Ok, modificado.

2021-06-10 01:23 UTC, FabriCubi commented on kafkaadmin/topics.go
> +	return tsf, nil
Ok, modificado.

2021-06-10 01:23 UTC, FabriCubi commented on kafkaadmin/topics.go
> +// is returned as a *TopicConfig,  this query kafka directly rather than zk.
Ok, modificado.

2021-06-10 01:23 UTC, FabriCubi commented on kafkaadmin/topics.go
> +	ret, er := c.c.DescribeConfigs(context.Background(),
ok, modificado.

2021-06-10 01:24 UTC, FabriCubi commented on kafkaadmin/topics.go
> +		return nil, ret[0].Error
ok, modificado.

2021-06-10 01:24 UTC, FabriCubi commented on kafkaadmin/topics.go
> +		Version: 1,
Ok, modificado.

2021-06-15 18:32 UTC, closed without merging